import Rodape from '@/components/Rodape'
import './globals.scss'
import Menu from '@/components/Menu'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Menu/>
      {children}
      <Rodape/>
    </html>
  )
}
